apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-engine
  template:
    metadata:
      labels:
        app: mpi-engine
    spec:
      containers:
        - name: mpi-engine
          image: irwinschmitt/jogo-da-vida-engine-mpi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-engine-service
spec:
  type: ClusterIP
  selector:
    app: mpi-engine
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
