apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-engine
  template:
    metadata:
      labels:
        app: spark-engine
    spec:
      containers:
        - name: spark-engine
          image: irwinschmitt/jogo-da-vida-engine-spark:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: spark-engine-service
spec:
  type: ClusterIP
  selector:
    app: spark-engine
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
