apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job-test-tam-8
spec:
  template:
    spec:
      containers:
        - name: spark-gameoflife-job
          image: irwinschmitt/jogo-da-vida-engine-spark:latest
          securityContext:
            runAsUser: 0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/opt/bitnami/spark/bin/spark-submit"]
          args:
            - "--master"
            - "spark://spark-master:7077"
            - "--conf"
            - "spark.driver.host=$(POD_IP)"
            - "/app/main.py"
            - "4"
      restartPolicy: Never
