apiVersion: v1
kind: Service
metadata:
  name: engine-spark-master
spec:
  ports:
    - name: spark-connect
      port: 7077
      targetPort: 7077
    - name: web-ui
      port: 8080
      targetPort: 8080
  selector:
    component: engine-spark-master
