apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: engine-spark-master
  template:
    metadata:
      labels:
        component: engine-spark-master
    spec:
      containers:
        - name: engine-spark-master
          image: irwinschmitt/jogo-da-vida-engine-spark:latest
          command: ["/opt/bitnami/spark/bin/spark-class"]
          args:
            - "org.apache.spark.deploy.master.Master"
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MASTER_HOST
              value: "0.0.0.0"
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
