replicas: 1
minimumMasterNodes: 1
discoveryType: "single-node"
clusterHealthCheckParams: "wait_for_status=yellow&timeout=10s"

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
