apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: quickstart-filebeat
spec:
  type: filebeat
  version: 8.14.1
  config:
    output.elasticsearch:
      hosts: ["http://quickstart-es-es-http:9200"]
      ssl.enabled: false
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          templates:
            - condition.or:
                - equals:
                    kubernetes.labels.app: "gateway"
                - equals:
                    kubernetes.labels.app: "spark-engine"
                - equals:
                    kubernetes.labels.app: "mpi-engine"
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    target: ""
                    overwrite_keys: false
                    add_error: true
                    max_depth: 1
              config:
                - type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
          - name: filebeat
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            securityContext:
              runAsUser: 0
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 200Mi
                cpu: 500m
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
                readOnly: true
              - name: varlibcontainerd
                mountPath: /var/lib/containerd
                readOnly: true
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: varlibcontainerd
            hostPath:
              path: /var/lib/containerd
