elasticsearch:
  hosts: ["elasticsearch-master.logging"]
  port: 9200
  protocol: "http"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: NodePort
  port: 5601
  nodePort: 30100
